version: "3.9"
services:
  firestore:
    image: mtlynch/firestore-emulator
    environment:
      FIRESTORE_PROJECT_ID: development
      PORT: 8200
  redis:
    image: redis
  job-manager:
    depends_on:
      - firestore
      - redis
    build:
      context: .
      dockerfile: job_manager/Dockerfile
    ports:
      - "8888:8080"
    environment:
      LOG_LEVEL: debug
      REDIS_ADDRESS: redis:6379
      PROJECT_ID: development
      FIRESTORE_PROJECT_ID: development
      FIRESTORE_EMULATOR_HOST: firestore_emulator:8200
  job-worker:
    depends_on:
      - firestore
      - redis
    build:
      context: .
      dockerfile: job_worker/Dockerfile
    environment:
      LOG_LEVEL: debug
      REDIS_ADDRESS: redis:6379
      PROJECT_ID: development
      FIRESTORE_PROJECT_ID: development
      FIRESTORE_EMULATOR_HOST: firestore_emulator:8200
  task-worker:
    depends_on:
      - firestore
      - redis
    build:
      context: .
      dockerfile: task_worker/Dockerfile
    environment:
      LOG_LEVEL: debug
      REDIS_ADDRESS: redis:6379
      PROJECT_ID: development
      FIRESTORE_PROJECT_ID: development
      FIRESTORE_EMULATOR_HOST: firestore_emulator:8200
