// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/smousa/forgerock-scheduler/api"

	mock "github.com/stretchr/testify/mock"
)

// JobProducer is an autogenerated mock type for the JobProducer type
type JobProducer struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, job
func (_m *JobProducer) Publish(ctx context.Context, job *api.JobRequest) error {
	ret := _m.Called(ctx, job)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.JobRequest) error); ok {
		r0 = rf(ctx, job)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
