// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/smousa/forgerock-scheduler/api"

	mock "github.com/stretchr/testify/mock"
)

// JobWorker is an autogenerated mock type for the JobWorker type
type JobWorker struct {
	mock.Mock
}

// Consume provides a mock function with given fields: ctx, job
func (_m *JobWorker) Consume(ctx context.Context, job *api.JobRequest) {
	_m.Called(ctx, job)
}
