// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/smousa/forgerock-scheduler/api"

	mock "github.com/stretchr/testify/mock"
)

// TaskWorker is an autogenerated mock type for the TaskWorker type
type TaskWorker struct {
	mock.Mock
}

// Consume provides a mock function with given fields: ctx, task
func (_m *TaskWorker) Consume(ctx context.Context, task *api.TaskRequest) {
	_m.Called(ctx, task)
}
