// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/smousa/forgerock-scheduler/api"

	mock "github.com/stretchr/testify/mock"
)

// TaskProducer is an autogenerated mock type for the TaskProducer type
type TaskProducer struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, task
func (_m *TaskProducer) Publish(ctx context.Context, task *api.TaskRequest) error {
	ret := _m.Called(ctx, task)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.TaskRequest) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
